name: CI Simple

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Ver archivos (DEBUG)
        run: ls -la

      - name: Ejecutar app
        run: node app.js

      - name: Ejecutar test
        run: node test.js
